# files
# learning 1 or all 4 machines ?
# learning and predicting only on FD01, reduces RMSE. -> thus we learn on all 4
data_directory: "data/"
train_files:
  - "train_FD001.txt"
  - "train_FD002.txt"
  - "train_FD003.txt"
  - "train_FD004.txt"
test_files:
  - "test_FD001.txt"
RUL_files:
  - "data/RUL_FD001.txt" 

# feature eng
use_features: true
reduce_by_not_relevant_sensor_data: true
add_special_features: false
rolling_window_size: 5

# model
model: 'xgBoost' # xgBoost

# general (here for lstm)
use_standard_scaler: false
sequence_length: 50